### ISSUE TITLE
Engine url should be provided over a stable interface and without any assumptions

### ISSUE THREAD

**Issue by alexsuter** [axonivy/project-build-plugin#25]
https://github.com/axonivy/project-build-plugin/blob/b51c709e54d8447f3f3893133121cdaecea66b94/src/main/java/ch/ivyteam/ivy/maven/engine/EngineControl.java#L196

Too many assumptions:
- there must be a log containing "info page of Axon.ivy Engine"
- Url starts with "http://" and ends with "/"
- Target url is always ended with "/ivy/" -> but in docker scenarios I want to have another one.

**Comment by ivy-rew** [comment]
right now the 'ivy' part is included to raise the probability that we only hit URLs being printed that are actually from the engine start. And not from a log of another library that runs at boot time.
But sure, we can slacken this assertion or even better, make it configurable for the end user.

**Comment by ivy-rew** [comment]
included it in a technical-dept story:
https://jira.axonivy.com/jira/browse/XIVY-3412
