### ISSUE TITLE
Automatic engine download using maven mechanisms? 

### ISSUE THREAD

**Issue by fbe** [axonivy/project-build-plugin#8]
Hey, just an idea for a small improvement:

we are using the project build plugin in an enterprise context. For security reasons our build pipelines have no internet access and everything must be downloaded from our own repositories.

Using the `ivy.engine.download.url` property (using the EngineDownloader) doesn't work for us because the mojo doesn't support http basic auth for the URLs to be used - and our company policies do not allow unauthenticated repository access. 

It would be possible to patch the plugin to allow basic auth credentials for the automatic engine downloader, but wouldn't it be better to deploy the engine zip files in a maven repository and obtain them using the normal maven artifact resolver api? Then, all security configurations in maven would work out of the box and no special configuration (except the version number of the engine) would be required.

Thanks!

**Comment by ivy-rew** [comment]
builds are running. should in some minutes be available in GAV repos
http://axonivy.github.io/project-build-plugin/snapshot/7.4/installEngine-mojo.html

**Comment by fbe** [comment]
Really cool, thank you for the quick release! =)
